### ISSUE TITLE
mongo_connector.errors.OperationFailed

### ISSUE THREAD

**Issue by ishare** [10gen-labs/mongo-connector#241] opened 2015-04-14 13:00 UTC
Could you help me solve this problem? My mongodb works fine, and `db.oplog.rs.find()` can get records.
And use `java -jar start.jar` start solr server. 
solr version: 5.0.0
mongo: 3.0.1

However, execute the following command, results in this errors.

$ mongo-connector -m localhost:27017 -t http://localhost:8983/solr -d solr_doc_manager

No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 8, in <module>
    load_entry_point('mongo-connector==2.1.dev0', 'console_scripts', 'mongo-connector')()
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/connector.py", line 998, in main
    conf.parse_args()
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/config.py", line 114, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/connector.py", line 789, in apply_doc_managers
    dm_instances.append(module.DocManager(target_url, **kwargs))
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 76, in __init__
    self._build_fields()
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 92, in _build_fields
    declared_fields = self.solr._send_request('get', ADMIN_URL)
  File "build/bdist.macosx-10.9-intel/egg/pysolr.py", line 322, in _send_request
mongo_connector.errors.OperationFailed: [Reason: Error 404 Not Found]

Thanks for your help!

**Comment by behackett** [comment] 2015-04-14 14:59
The problem isn't your MongoDB deployment. It seems Solr isn't running. That error is from pysolr. It doesn't seem to be able to connect to your solr resource at http://localhost:8983/solr.

**Comment by ishare** [comment] 2015-04-15 02:27
Solr is working, and I can access the web page from http://localhost:8983/solr.

**Comment by ishare** [comment] 2015-04-15 07:12
I change the cmd to:
$ mongo-connector -m 127.0.0.1:27017 -t http://localhost:8983/solr/xxx_shard1_replica1 -d solr_doc_manager

Logging to mongo-connector.log.

hang after this sentense! but no log print out.
Could you help me solve it ?

**Comment by ishare** [comment] 2015-04-15 09:55
when I do db.xx.insert(). I find below log from tomcat log, no logs found in mongo-connector.log.

0:0:0:0:0:0:0:1 - - [15/Apr/2015:17:51:39 +0800] "POST /solr/core0/update/?commit=false HTTP/1.1" 200 158

**Comment by ishare** [comment] 2015-04-15 12:39
I found it's not commit.. and I use --auto-commit-interval=0, but it still post `/solr/core0/update/?commit=false`

How to force it to do `/solr/core0/update/?commit=true` every post?

**Comment by llvtt** [comment] 2015-04-15 14:37
@ishare 
The Exception you're observing means that Mongo Connector couldn't obtain the schema for Solr. Mongo Connector uses the "LukeRequestHandler" to get the schema; see https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20Solr#mongo-connector-and-schemaxml. If you're using "http://localhost:8983/solr" as the base URL, then Mongo Connector will send a GET request to "http://localhost:8983/solr/admin/luke" to obtain the schema.

Are you running a multi-core setup on Solr? If so, you should point mongo-connector at the base URL for that core. E.g., for "core1":

    mongo-connector -d solr_doc_manager -t http://localhost:8983/solr/core1 ...

Also, what version of Solr are you using?

**Comment by llvtt** [comment] 2015-04-15 16:31
@ishare 
Sorry, I just noticed you'd already changed the target URL to have the core name in it. You're getting `200` responses back from Solr, so that means that it's working. Mongo Connector doesn't print out logs to STDOUT by default anymore, so you have to tail the log to see what's going on:

    tail -f mongo-connector.log

If you want to commit on every operation, the recomended way to do this is to modify `solrconfig.xml`. There's also a [`--auto-commit-interval`](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#docmanagersindexautocommitinterval) option you can use. See https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20Solr#managing-commit-behavior.

**Comment by ishare** [comment] 2015-04-16 06:03
There are two problems:
1. --auto-commit-interval=0 doesn't work, I tried serval times, everytime I insert data, it still posts /solr/solr/update/?commit=false.
2. mongo-connector.log doesn't record any insert or received data log by default. I insert serval data into mongodb, log file is still empty. I force to use -v option to get the debug and info logs..

**Comment by llvtt** [comment] 2015-04-16 18:45
@ishare 
Have you tried increasing the verbosity? The Solr DocManager doesn't log anything by default unless there are Exceptions. See https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#verbosity.

As for the commit behavior, the preferred way to configure this is directly in solrconfig.xml. See http://wiki.apache.org/solr/SolrConfigXml#Update_Handler_Section. That being said, I just patched a bug for `autoCommitInterval` when set to 0. This should be fixed now in master.

**Comment by ishare** [comment] 2015-04-17 03:37
Thanks, I could get the debug and info logs using -v option.
And I have a question, how can I choose which mongo database or collection to sync to solr?

**Comment by llvtt** [comment] 2015-04-20 17:34
Have a look at [namespace configuration](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#configure-namespaces).

**Closed** 2015-04-25 16:33 UTC
